# Outguess服务端配置
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    max-connections: 8192

spring:
  application:
    name: outguess-server
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Outguess配置
outguess:
  max-file-size: 10485760  # 10MB
  max-message-size: 1048576  # 1MB
  temp-dir: ${java.io.tmpdir}
  enable-verbose-logging: false
  max-concurrent-requests: 10

# 日志配置
logging:
  level:
    com.outguess: INFO
    org.springframework: WARN
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/outguess-server.log
    max-size: 100MB
    max-history: 30

# 管理端点
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized